---
title: Comparison of data dimensionality reduction methods
author: Yu Cao
date: '2021-08-20'
slug: comparison-of-data-dimensionality-reduction-methods
categories:
  - Data Mining
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-06T16:52:39+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
```

```{r message=FALSE, results='hide',warning=FALSE, echo=TRUE, }
billboard <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/billboard.csv")

audio_features <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/audio_features.csv")
```

```{r, message=FALSE, warning=FALSE, results='hide'}
max_weeks <- billboard %>% 
  group_by(song_id) %>% 
  summarise(weeks_on_chart = max(weeks_on_chart))

billboard_joined <- audio_features %>% 
  filter(!is.na(danceability)) %>% 
  inner_join(max_weeks, by = "song_id")
```

```{r, warning=FALSE, message=FALSE}
billboard_joined %>% 
  ggplot(aes(tempo, fill = factor(time_signature))) + 
  geom_histogram(alpha = 0.6, position = "identity", bins = 30)
```

```{r, message=FALSE, warning=FALSE, results='hide'}
library(corrr)

billboard_joined %>% 
  select(danceability:weeks_on_chart) %>% 
  na.omit() %>% 
  correlate() %>% 
  rearrange() %>% 
  network_plot(colors = c("orange", "white", "midnightblue"))
```

```{r}
head(billboard)
```

```{r}
billboard %>% 
  filter(song_id == "Don't Just Stand There") %>% 
  ggplot(aes(previous_week_position, week_position)) + 
  geom_line()
```

```{r}
df <- read_csv("https://raw.githubusercontent.com/YuCao16/about_me/main/train.csv")
```
